# Review Equities

* get sector historical data
  - get top firms in sector
* standardize / normalize across credit cycles

* get 10Qs for firms

In [62]:
import pandas as pd
import yfinance as yf

### Sector: Technology

In [2]:
tech = yf.Sector('technology')

^: the caret often denotes an index or benchmark on financial sites.
YH: identifier for Yahoo Finance.
311: represents the Technology Sector

In [8]:
tech.symbol, tech.ticker

('^YH311', yfinance.Ticker object <^YH311>)

In [5]:
tech.overview

{'companies_count': 830,
 'market_cap': 23308099649536,
 'message_board_id': 'INDEXYH311',
 'description': 'Companies engaged in the design, development, and support of computer operating systems and applications. This sector also includes companies that make computer equipment, data storage products, networking products, semiconductors, and components. Companies in this sector include Apple, Microsoft, and IBM.',
 'industries_count': 12,
 'market_weight': 0.30255747,
 'employee_count': 7075758}

In [4]:
tech.industries

,name,symbol,market weight
key,,,
semiconductors,Semiconductors,^YH31130020,0.332077
software-infrastructure,Software - Infrastructure,^YH31110030,0.249057
consumer-electronics,Consumer Electronics,^YH31120030,0.173632
software-application,Software - Application,^YH31110020,0.100680
information-technology-services,Information Technology Services,^YH31110010,0.033991
semiconductor-equipment-materials,Semiconductor Equipment & Materials,^YH31130010,0.030154
communication-equipment,Communication Equipment,^YH31120010,0.024543
computer-hardware,Computer Hardware,^YH31120020,0.022815
electronic-components,Electronic Components,^YH31120040,0.020173
scientific-technical-instruments,Scientific & Technical Instruments,^YH31120060,0.009130
solar,Solar,^YH31130030,0.002557
electronics-computer-distribution,Electronics & Computer Distribution,^YH31120050,0.001191

A company's market weight (or market-cap weight) refers to its proportion of an index, determined by its total market value (market capitalization) compared to the total value of all companies in that index, meaning larger companies naturally have a greater influence on the index's movement.

In [13]:
firms = tech.top_companies
pct_of_sector = firms['market weight'].sum()
print(f'Percent of sector is represented by sum of market weights: {round(pct_of_sector,4)*100}')
firms.head(5)

Percent of sector is represented by sum of market weights: 88.19

                         name      rating  market weight
symbol
NVDA       NVIDIA Corporation  Strong Buy       0.189645
AAPL               Apple Inc.         Buy       0.174789
MSFT    Microsoft Corporation  Strong Buy       0.155446
AVGO            Broadcom Inc.  Strong Buy       0.069174
ORCL       Oracle Corporation         Buy       0.023737

In [31]:
firm_name = tech.research_reports[0]['headHtml'].split('Analyst Report: ')[1]
print(f'reports count: {len(tech.research_reports)}')
print(firm_name)
tech.research_reports[0]

reports count: 4
Micron Technology, Inc.

{'id': 'MS_0P000003MC_AnalystReport_1766190920000',
 'headHtml': 'Analyst Report: Micron Technology, Inc.',
 'provider': 'Morningstar',
 'targetPrice': 225.0,
 'targetPriceStatus': 'Maintained',
 'investmentRating': 'Bearish',
 'reportDate': '2025-12-20T00:35:20Z',
 'reportTitle': 'Micron is one of the largest semiconductor companies in the world, specializing in memory and storage chips. Its primary revenue stream comes from dynamic random access memory, or DRAM, and it also has minority exposure to not-and or NAND, flash chips. Micron serves a global customer base, selling chips into data centers, mobile phones, consumer electronics, and industrial and automotive applications. The firm is vertically integrated. ',
 'reportType': 'Analyst Report'}

### Firm (Ticker): Nividia

In [17]:
nvda = yf.Ticker('NVDA')

In [20]:
[item for item in dir(nvda) if '_' not in item]

['actions',
 'balancesheet',
 'calendar',
 'cashflow',
 'dividends',
 'earnings',
 'financials',
 'history',
 'incomestmt',
 'info',
 'isin',
 'live',
 'news',
 'options',
 'recommendations',
 'session',
 'shares',
 'splits',
 'sustainability',
 'ticker',
 'ws']

In [23]:
print( f'{nvda.info['sector']} / {nvda.info['industry']}' )
nvda.info

Technology / Semiconductors

{'address1': '2788 San Tomas Expressway',
 'city': 'Santa Clara',
 'state': 'CA',
 'zip': '95051',
 'country': 'United States',
 'phone': '408 486 2000',
 'website': 'https://www.nvidia.com',
 'industry': 'Semiconductors',
 'industryKey': 'semiconductors',
 'industryDisp': 'Semiconductors',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': "NVIDIA Corporation, a computing infrastructure company, provides graphics and compute and networking solutions in the United States, Singapore, Taiwan, China, Hong Kong, and internationally. The Compute & Networking segment includes its Data Centre accelerated computing platforms and artificial intelligence solutions and software; networking; automotive platforms and autonomous and electric vehicle solutions; Jetson for robotics and other embedded platforms; and DGX Cloud computing services. The Graphics segment offers GeForce GPUs for gaming and PCs, the GeForce NOW game streaming service and related infrastructure, and solutions for gaming platforms; Quadro/NVIDIA RTX GPUs for enterprise workstation graphics; virtual GPU or vGPU software for cloud-based visual and virtual computing; automotive platforms for infotainment systems; and Omniverse software for building and operating industrial AI and digital twin applications. It also customized agentic solutions designed in collaboration with NVIDIA to accelerate enterprise AI adoption. The company's products are used in gaming, professional visualization, data center, and automotive markets. It sells its products to original equipment manufacturers, original device manufacturers, system integrators and distributors, independent software vendors, cloud service providers, consumer internet companies, add-in board manufacturers, distributors, automotive manufacturers and tier-1 automotive suppliers, and other ecosystem participants. NVIDIA Corporation was incorporated in 1993 and is headquartered in Santa Clara, California.",
 'fullTimeEmployees': 36000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Jen-Hsun  Huang',
   'age': 61,
   'title': 'Co-Founder, CEO, President & Director',
   'yearBorn': 1963,
   'fiscalYear': 2025,
   'totalPay': 11054945,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Colette M. Kress',
   'age': 57,
   'title': 'Executive VP & CFO',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1512641,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Debora  Shoquist',
   'age': 69,
   'title': 'Executive Vice President of Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 1379071,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Timothy S. Teter J.D.',
   'age': 57,
   'title': 'Executive VP, General Counsel & Secretary',
   'yearBorn': 1967,
   'fiscalYear': 2025,
   'totalPay': 1362989,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Ajay K. Puri',
   'age': 69,
   'title': 'Executive Vice President of Worldwide Field Operations',
   'yearBorn': 1955,
   'fiscalYear': 2025,
   'totalPay': 2313851,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Chris A. Malachowsky',
   'title': 'Co-Founder',
   'fiscalYear': 2025,
   'totalPay': 320000,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Donald F. Robertson Jr.',
   'age': 55,
   'title': 'VP & Chief Accounting Officer',
   'yearBorn': 1969,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Prof. William J. Dally Ph.D.',
   'age': 63,
   'title': 'Chief Scientist & Senior VP of Research',
   'yearBorn': 1961,
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Toshiya  Hari',
   'title': 'Vice President of Investor Relations & Strategic Finance',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Mylene  Mangalindan',
   'title': 'VP of Corporate Communications',
   'fiscalYear': 2025,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 5,
 'boardRisk': 10,
 'compensationRisk': 4,
 'shareHolderRightsRisk': 8,
 'overallRisk': 8,
 'governanceEpochDate': 1764547200,
 'compensationAsOfEpochDate': 1767139200,
 'irWebsite': 'http://phx.corporate-ir.net/phoenix.zhtml?c=116466&p=irol-IRHome',
 'executiveTeam': [],
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 174.14,
 'open': 176.665,
 'dayLow': 176.35,
 'dayHigh': 181.45,
 'regularMarketPreviousClose': 174.14,
 'regularMarketOpen': 176.665,
 'regularMarketDayLow': 176.35,
 'regularMarketDayHigh': 181.45,
 'dividendRate': 0.04,
 'dividendYield': 0.02,
 'exDividendDate': 1764806400,
 'payoutRatio': 0.0099,
 'fiveYearAvgDividendYield': 0.06,
 'beta': 2.284,
 'trailingPE': 44.799507,
 'forwardPE': 24.15835,
 'volume': 264623530,
 'regularMarketVolume': 264623530,
 'averageVolume': 192957357,
 'averageVolume10days': 193490240,
 'averageDailyVolume10Day': 193490240,
 'bid': 171.04,
 'ask': 171.64,
 'bidSize': 1,
 'askSize': 1,
 'marketCap': 4406563569664,
 'fiftyTwoWeekLow': 86.62,
 'fiftyTwoWeekHigh': 212.19,
 'allTimeHigh': 212.19,
 'allTimeLow': 0.033333,
 'priceToSalesTrailing12Months': 23.54663,
 'fiftyDayAverage': 185.6516,
 'twoHundredDayAverage': 157.561,
 'trailingAnnualDividendRate': 0.04,
 'trailingAnnualDividendYield': 0.00022970024,
 'currency': 'USD',
 'tradeable': False,
 'enterpriseValue': 4348270870528,
 'profitMargins': 0.53007,
 'floatShares': 23329944000,
 'sharesOutstanding': 24305000000,
 'sharesShort': 232898275,
 'sharesShortPriorMonth': 238599888,
 'sharesShortPreviousMonthDate': 1761868800,
 'dateShortInterest': 1764288000,
 'sharesPercentSharesOut': 0.0095999995,
 'heldPercentInsiders': 0.04329,
 'heldPercentInstitutions': 0.69368,
 'shortRatio': 1.05,
 'shortPercentOfFloat': 0.01,
 'impliedSharesOutstanding': 24347000000,
 'bookValue': 4.892,
 'priceToBook': 36.99714,
 'lastFiscalYearEnd': 1737849600,
 'nextFiscalYearEnd': 1769385600,
 'mostRecentQuarter': 1761436800,
 'earningsQuarterlyGrowth': 0.653,
 'netIncomeToCommon': 99198001152,
 'trailingEps': 4.04,
 'forwardEps': 7.49182,
 'lastSplitFactor': '10:1',
 'lastSplitDate': 1717977600,
 'enterpriseToRevenue': 23.235,
 'enterpriseToEbitda': 38.584,
 '52WeekChange': 0.29584014,
 'SandP52WeekChange': 0.14402747,
 'lastDividendValue': 0.01,
 'lastDividendDate': 1764806400,
 'quoteType': 'EQUITY',
 'currentPrice': 180.99,
 'targetHighPrice': 352.0,
 'targetLowPrice': 140.0,
 'targetMeanPrice': 253.01825,
 'targetMedianPrice': 250.0,
 'recommendationMean': 1.32812,
 'recommendationKey': 'strong_buy',
 'numberOfAnalystOpinions': 57,
 'totalCash': 60608000000,
 'totalCashPerShare': 2.494,
 'ebitda': 112696000512,
 'totalDebt': 10821999616,
 'quickRatio': 3.605,
 'currentRatio': 4.468,
 'totalRevenue': 187141996544,
 'debtToEquity': 9.102,
 'revenuePerShare': 7.668,
 'returnOnAssets': 0.53528,
 'returnOnEquity': 1.07359,
 'grossProfits': 131092996096,
 'freeCashflow': 53282873344,
 'operatingCashflow': 83158999040,
 'earningsGrowth': 0.667,
 'revenueGrowth': 0.625,
 'grossMargins': 0.7005,
 'ebitdaMargins': 0.60220003,
 'operatingMargins': 0.63168997,
 'financialCurrency': 'USD',
 'symbol': 'NVDA',
 'language': 'en-US',
 'region': 'US',
 'typeDisp': 'Equity',
 'quoteSourceName': 'Nasdaq Real Time Price',
 'triggerable': True,
 'customPriceAlertConfidence': 'HIGH',
 'marketState': 'CLOSED',
 'hasPrePostMarketData': True,
 'firstTradeDateMilliseconds': 917015400000,
 'postMarketChangePercent': 0.20995061,
 'postMarketPrice': 181.37,
 'postMarketChange': 0.37998962,
 'regularMarketChange': 6.85001,
 'regularMarketDayRange': '176.35 - 181.45',
 'shortName': 'NVIDIA Corporation',
 'longName': 'NVIDIA Corporation',
 'exchange': 'NMS',
 'messageBoardId': 'finmb_32307',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EST',
 'gmtOffSetMilliseconds': -18000000,
 'market': 'us_market',
 'esgPopulated': False,
 'regularMarketChangePercent': 3.93362,
 'regularMarketPrice': 180.99,
 'corporateActions': [],
 'postMarketTime': 1766192399,
 'regularMarketTime': 1766178002,
 'fullExchangeName': 'NasdaqGS',
 'averageDailyVolume3Month': 192957357,
 'fiftyTwoWeekLowChange': 94.37,
 'fiftyTwoWeekLowChangePercent': 1.0894712,
 'fiftyTwoWeekRange': '86.62 - 212.19',
 'fiftyTwoWeekHighChange': -31.199997,
 'fiftyTwoWeekHighChangePercent': -0.14703801,
 'fiftyTwoWeekChangePercent': 29.584015,
 'dividendDate': 1766707200,
 'earningsTimestamp': 1772053200,
 'earningsTimestampStart': 1772053200,
 'earningsTimestampEnd': 1772053200,
 'earningsCallTimestampStart': 1763589600,
 'earningsCallTimestampEnd': 1763589600,
 'isEarningsDateEstimate': False,
 'epsTrailingTwelveMonths': 4.04,
 'epsForward': 7.49182,
 'epsCurrentYear': 4.68975,
 'priceEpsCurrentYear': 38.592674,
 'fiftyDayAverageChange': -4.6615906,
 'fiftyDayAverageChangePercent': -0.025109349,
 'twoHundredDayAverageChange': 23.429,
 'twoHundredDayAverageChangePercent': 0.14869797,
 'sourceInterval': 15,
 'exchangeDataDelayedBy': 0,
 'prevName': 'Usual Stablecoin',
 'nameChangeDate': '2025-12-20',
 'averageAnalystRating': '1.3 - Strong Buy',
 'cryptoTradeable': False,
 'displayName': 'NVIDIA',
 'trailingPegRatio': 0.6921}

Get all available option expiration dates.

In [90]:
expiration_dates = nvda.options[:3]
print(f"Available expiration dates: {expiration_dates}")

Available expiration dates: ('2025-12-26', '2026-01-02', '2026-01-09')

An option chain (or option matrix) is a table that lists all available option contracts for a specific underlying security, organized by expiration date and strike price.

The option chain provides a snapshot of crucial information for traders. Key data points typically include: 
* Strike Price: The predetermined price at which the option holder can buy (call) or sell (put) the underlying asset.
* Expiration Date: The date the contract expires. Options with less time until expiration lose value faster due to time decay (theta).
* Calls and Puts: The chain is separated into sections for call options (right to buy) and put options (right to sell).
* Bid and Ask: The highest price a buyer is willing to pay (bid) and the lowest price a seller is willing to accept (ask).
* Last Price: The price at which the most recent trade occurred.
* Volume: The total number of contracts traded during the current day.
* Open Interest (OI): The total number of outstanding contracts that have not yet been closed or exercised.
* Implied Volatility (IV): The market's forecast of the underlying asset's volatility, derived from the option's price.
* "The Greeks": Some platforms include risk measures like Delta, Gamma, Theta, and Vega, which quantify how sensitive the option's price is to various factors.

In [88]:
option_chain = nvda.option_chain()
option_chain.calls.head(3)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,NVDA251226C00050000,2025-12-19 19:50:38+00:00,50.0,130.65,130.0,131.60,5.429993,4.336362,9.0,71,5.183597,True,REGULAR,USD
1,NVDA251226C00055000,2025-12-12 16:09:36+00:00,55.0,122.34,124.3,127.35,0.000000,0.000000,5.0,7,5.583987,True,REGULAR,USD
2,NVDA251226C00060000,2025-12-19 15:23:42+00:00,60.0,117.56,119.3,122.15,-7.389999,-5.914365,2.0,11,5.041019,True,REGULAR,USD

In [89]:
option_chain.puts.head(3)

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,NVDA251226P00050000,2025-12-19 19:10:47+00:00,50.0,0.01,0.0,0.01,0.0,0.0,2.0,104.0,3.062502,False,REGULAR,USD
1,NVDA251226P00055000,2025-12-11 15:03:14+00:00,55.0,0.01,0.0,0.01,0.0,0.0,10.0,6018.0,2.875003,False,REGULAR,USD
2,NVDA251226P00060000,2025-11-28 15:03:36+00:00,60.0,0.01,0.0,0.01,0.0,0.0,1.0,368.0,2.625003,False,REGULAR,USD

### Multiple Firms (Tickers)

In [44]:
tickers = firms.index.to_list()[:10]
top_ten = yf.download(tickers, period="max")

/tmp/ipykernel_65883/709460836.py:2: FutureWarning: YF.download() has changed argument auto_adjust default to True
  top_ten = yf.download(tickers, period="max")
[*********************100%***********************]  10 of 10 completed

In [73]:
def separate_batch_call_to_dict_of_dfs(batch_tickers):
    """..."""
    top_lvls = list( set( batch_tickers.columns.get_level_values(0)) )
    symbols = list( set( batch_tickers.columns.get_level_values(1)) )
    dfs = {}
    for symbol in symbols:
        df = pd.DataFrame()
        for idx, lvl in enumerate(top_lvls):
            tmp = batch_tickers.loc[:, (lvl, symbol)]
            df.insert(idx, lvl, tmp)
        dfs[symbol] = df
    return dfs

dfs = separate_batch_call_to_dict_of_dfs(top_ten)

In [75]:
dfs['AAPL'].tail()

                   Low       Volume       Close        High        Open
Date
2025-12-15  272.839996   50409100.0  274.109985  280.149994  280.149994
2025-12-16  271.790009   37648600.0  274.609985  275.500000  272.820007
2025-12-17  271.640015   50138700.0  271.839996  276.160004  275.010010
2025-12-18  266.950012   51630700.0  272.190002  273.630005  273.609985
2025-12-19  269.899994  144599200.0  273.670013  274.600006  272.149994

In [77]:
tks = yf.Tickers(tickers)
tmp = tks.download(period='max')

[*********************100%***********************]  10 of 10 completed

In [81]:
[item for item in dir(tks) if '_' not in item]

['download', 'history', 'live', 'news', 'symbols', 'tickers', 'ws']

In [85]:
tks.symbols

['NVDA', 'AAPL', 'MSFT', 'AVGO', 'ORCL', 'PLTR', 'AMD', 'CSCO', 'MU', 'IBM']